<?php
declare(strict_types=1);
$labels=['overview'=>'Overview','users'=>'Users','roles'=>'Roles & Permissions','service-health'=>'Service Health','destinations'=>'Destinations','security'=>'Security','email'=>'Email','log'=>'Log'];
$adminBase='/admin';
$readOnly=!can('Administrator');
$roles=db()->query('SELECT r.*,(SELECT COUNT(*) FROM users u WHERE u.role_id=r.id) user_count FROM roles r ORDER BY built_in DESC,name')->fetchAll(PDO::FETCH_ASSOC);
$users=db()->query('SELECT u.*,r.name role_name FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.username')->fetchAll(PDO::FETCH_ASSOC);
$destinations=db()->query('SELECT * FROM destinations ORDER BY type,name')->fetchAll(PDO::FETCH_ASSOC);
$pushStatus=pushover_status();$mailStatus=smtp_probe();
function admin_nav(string $section,array $labels,string $base): void {echo'<aside class="admin-sidebar"><p class="eyebrow">Administration</p><h2>Administration</h2><nav class="ui vertical fluid menu">';foreach($labels as$key=>$label)echo'<a class="item '.($section===$key?'active teal':'').'" href="'.$base.'?section='.$key.'">'.h($label).'</a>';echo'</nav><p class="sidebar-note">Manage access, delivery services, system email, security, and audit history.</p></aside>';}
page_start($labels[$section].' · Administration');
?>
<div class="admin-shell">
<?php admin_nav($section,$labels,$adminBase);?>
<div class="admin-content"><p class="eyebrow">Administration</p><h1><?=h($labels[$section])?></h1>
<?php if($message):?><p class="notice"><?=h($message)?></p><?php endif;?>
<?php if(isset($_SESSION['generated_password'])):?><div class="notice secret-once"><strong>Generated Password</strong><code><?=h((string)$_SESSION['generated_password'])?></code><span>Copy this password now. It will not be displayed again.</span></div><?php unset($_SESSION['generated_password']);endif;?>

<?php if($section==='overview'):
$counts=['Users'=>(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn()+1,'Roles'=>(int)db()->query('SELECT COUNT(*) FROM roles')->fetchColumn(),'Inbound Rules'=>(int)db()->query('SELECT COUNT(*) FROM rules')->fetchColumn(),'Outbound Templates'=>(int)db()->query('SELECT COUNT(*) FROM outbound_templates')->fetchColumn(),'Destinations'=>(int)db()->query('SELECT COUNT(*) FROM destinations')->fetchColumn()];?>
<div class="metric-grid"><?php foreach($counts as$label=>$count):?><article class="metric-card"><span class="metric-value"><?=$count?></span><span><?=h($label)?></span></article><?php endforeach;?></div>
<section class="card"><h2>Notification Routing At A Glance</h2><p>Inbound rules decide whether a payload matches. Outbound templates format the notification. Destinations hold the delivery configuration used by those templates.</p><div class="status-row"><span>Pushover <span class="indicator <?=$pushStatus['level']?>"><?=h($pushStatus['label'])?></span></span><span>Email <span class="indicator <?=$mailStatus['level']?>"><?=h($mailStatus['label'])?></span></span></div></section>

<?php elseif($section==='users'):
$editId=(int)($_GET['edit']??0);$editUser=null;foreach($users as$u)if((int)$u['id']===$editId)$editUser=$u;?>
<section class="card"><div class="tilehead"><h2>User Directory</h2><?php if(!$readOnly):?><a class="button" href="<?=$adminBase?>?section=users#user-form">New User</a><?php endif;?></div><div class="table"><table><thead><tr><th>User</th><th>Role</th><th>Account</th><th>2FA</th><th>Actions</th></tr></thead><tbody><tr><td><strong>Legacy Administrator</strong><br><span>admin · Recovery Account</span></td><td>Administrator</td><td>Enabled</td><td>Recovery Bypass</td><td><span class="ui label">Protected</span></td></tr><?php foreach($users as$u):?><tr><td><strong><?=h($u['full_name'])?></strong><br><span><?=h($u['username'])?> · <?=h($u['email'])?></span></td><td><?=h($u['role_name'])?></td><td><?=$u['enabled']?'Enabled':'Disabled'?></td><td><?=$u['two_factor_secret']?'Registered':'Not Registered'?></td><td><a class="button secondary small" href="?section=users&amp;edit=<?=$u['id']?>#user-form">Edit</a><?php if(!$readOnly):?><form method="post" class="inline" onsubmit="return confirm('Delete this user?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="danger small">Delete</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if(!$readOnly):?><section class="card" id="user-form"><h2><?=$editUser?'Edit User':'Create User'?></h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_user"><input type="hidden" name="id" value="<?=$editUser['id']??0?>"><label>Username<input name="username" required value="<?=h((string)($editUser['username']??''))?>" pattern="[A-Za-z0-9_.-]{3,64}"></label><label>Full Name<input name="full_name" required value="<?=h((string)($editUser['full_name']??''))?>"></label><label>Email Address<input type="email" name="email" required value="<?=h((string)($editUser['email']??''))?>"></label><label>Role<select name="role_id"><?php foreach($roles as$r):?><option value="<?=$r['id']?>" <?=((int)($editUser['role_id']??0)===(int)$r['id']||(!$editUser&&$r['name']==='User'))?'selected':''?>><?=h($r['name'])?></option><?php endforeach;?></select></label><?php if(!$editUser):?><label class="check wide"><input type="checkbox" name="email_reset" checked> Email The User A Password Reset Link</label><p class="wide help">Untick this option to generate and display a one-time 16-character password after saving.</p><?php endif;?><label class="check wide"><input type="checkbox" name="enabled" <?=$editUser&&$editUser['enabled']?'checked':''?>> Account Enabled</label><div class="wide"><button>Save User</button></div></form></section><?php endif;?>

<?php elseif($section==='roles'):
$editId=(int)($_GET['edit']??0);$editRole=null;foreach($roles as$r)if((int)$r['id']===$editId)$editRole=$r;$selected=$editRole?role_permissions((int)$editRole['id']):[];?>
<div class="split-grid"><section class="card"><h2>Configured Roles</h2><?php foreach($roles as$r):?><div class="role-row"><strong><?=h($r['name'])?></strong><span><?=count(role_permissions((int)$r['id']))?> Permissions · <?=$r['user_count']?> Users</span><p><?=$r['built_in']?($r['name']==='Administrator'?'Built-in role · Access All Areas':'Built-in role'):'Custom role'?></p><?php if(!$r['built_in']&&!$readOnly):?><a class="button secondary small" href="?section=roles&amp;edit=<?=$r['id']?>">Edit Role</a><form method="post" class="inline" onsubmit="return confirm('Delete this role?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_role"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger small">Delete</button></form><?php endif;?></div><?php endforeach;?></section>
<section class="card"><h2>Role Permissions</h2><?php if($readOnly):?><p>Read-only administrators can inspect roles but cannot change them.</p><?php elseif($editRole&&$editRole['built_in']):?><p>Built-in roles are fixed. Create a custom role for a different permission set.</p><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_role"><input type="hidden" name="id" value="<?=$editRole['id']??0?>"><label>Role Name<input name="name" required value="<?=h((string)($editRole['name']??''))?>"></label><div class="permission-grid"><?php foreach(PERMISSIONS as$permission):?><label class="check permission"><input type="checkbox" name="permissions[]" value="<?=h($permission)?>" <?=in_array($permission,$selected,true)?'checked':''?>> <?=h($permission)?></label><?php endforeach;?></div><button>Save Role</button></form><?php endif;?></section></div>

<?php elseif($section==='service-health'):?>
<div class="grid services"><section class="card"><div class="tilehead"><h2>Pushover</h2><span class="indicator <?=$pushStatus['level']?>"><?=h($pushStatus['label'])?></span></div><p><?=h($pushStatus['note'])?></p></section><section class="card"><div class="tilehead"><h2>Email</h2><span class="indicator <?=$mailStatus['level']?>"><?=h($mailStatus['label'])?></span></div><p><?=h($mailStatus['note'])?></p></section></div>
<section class="card"><h2>Operational Checks</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="service_health"><label class="check wide"><input type="checkbox" name="pushover_operational" <?=setting('pushover_operational','0')==='1'?'checked':''?> <?=$readOnly?'disabled':''?>> Enable Pushover Operational Status</label><label class="wide">Pushover RSS Service Status Feed<input type="url" name="pushover_status_rss" value="<?=h(setting('pushover_status_rss','https://status.pushover.net/rss'))?>" <?=$readOnly?'readonly':''?>></label><label class="check wide"><input type="checkbox" name="email_operational" <?=setting('email_operational','0')==='1'?'checked':''?> <?=$readOnly?'disabled':''?>> Enable Email Operational Status</label><label>SMTP Test Hostname<input name="smtp_test_host" value="<?=h(setting('smtp_test_host'))?>" <?=$readOnly?'readonly':''?>></label><label>SMTP Test Port<input type="number" name="smtp_test_port" value="<?=h(setting('smtp_test_port','587'))?>" <?=$readOnly?'readonly':''?>></label><label class="wide">Email Provider Status Page<input type="url" name="smtp_status_url" value="<?=h(setting('smtp_status_url'))?>" <?=$readOnly?'readonly':''?>></label><p class="wide help">A service can only be enabled when at least one enabled destination of that type exists.</p><?php if(!$readOnly):?><div class="wide"><button>Save And Run Checks</button></div><?php endif;?></form></section>

<?php elseif($section==='destinations'):
$editId=(int)($_GET['edit']??0);$editDestination=null;$editConfig=[];foreach($destinations as$d)if((int)$d['id']===$editId){$editDestination=$d;$editConfig=json_decode($d['configuration'],true)?:[];}?>
<section class="card"><div class="tilehead"><h2>Configured Destinations</h2><?php if(!$readOnly):?><a class="button" href="#destination-form">New Destination</a><?php endif;?></div><div class="table"><table><thead><tr><th>Name</th><th>Type</th><th>Description</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($destinations as$d):?><tr><td><?=h($d['name'])?></td><td><?=h(ucfirst($d['type']))?></td><td><?=h($d['description'])?></td><td><?=$d['enabled']?'Enabled':'Disabled'?></td><td><a class="button secondary small" href="?section=destinations&amp;edit=<?=$d['id']?>#destination-form">Edit</a><?php if(!$readOnly):?><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="test_destination"><input type="hidden" name="id" value="<?=$d['id']?>"><button class="small">Test</button></form><form method="post" class="inline" onsubmit="return confirm('Delete this destination?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_destination"><input type="hidden" name="id" value="<?=$d['id']?>"><button class="danger small">Delete</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$destinations):?><tr><td colspan="5">No Destinations Yet</td></tr><?php endif;?></tbody></table></div></section>
<?php if(!$readOnly):?><section class="card" id="destination-form"><h2><?=$editDestination?'Edit Destination':'Create Destination'?></h2><form method="post" class="form-grid" data-destination-form><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_destination"><input type="hidden" name="id" value="<?=$editDestination['id']??0?>"><label>Name<input name="name" required value="<?=h((string)($editDestination['name']??''))?>"></label><label>Type<select name="type" data-destination-type><option value="pushover" <?=($editDestination['type']??'pushover')==='pushover'?'selected':''?>>Pushover</option><option value="email" <?=($editDestination['type']??'')==='email'?'selected':''?>>Email</option></select></label><label class="wide">Short Description<input name="description" value="<?=h((string)($editDestination['description']??''))?>"></label><div class="wide destination-fields" data-type="pushover"><label>User Or Group Key<input type="password" name="user_key" placeholder="<?=$editDestination?'Leave blank to keep current value':''?>"></label><label>Application Key<input type="password" name="app_key" placeholder="<?=$editDestination?'Leave blank to keep current value':''?>"></label></div><div class="wide destination-fields form-grid" data-type="email"><label>SMTP Server<input name="smtp_host" value="<?=h((string)($editConfig['smtp_host']??''))?>"></label><label>Server Port<input type="number" name="smtp_port" value="<?=h((string)($editConfig['smtp_port']??'587'))?>"></label><label>Connection Security<select name="smtp_security"><option value="starttls">STARTTLS</option><option value="ssl">TLS/SSL</option><option value="none">None</option></select></label><label>Username<input name="smtp_user" value="<?=h((string)($editConfig['smtp_user']??''))?>"></label><label>Password<input type="password" name="password" placeholder="<?=$editDestination?'Leave blank to keep current value':''?>"></label><label>Sender Name<input name="sender_name" value="<?=h((string)($editConfig['sender_name']??''))?>"></label><label>Sender Email<input type="email" name="sender_email" value="<?=h((string)($editConfig['sender_email']??''))?>"></label><label>Recipient Name<input name="recipient_name" value="<?=h((string)($editConfig['recipient_name']??''))?>"></label><label>Recipient Email<input type="email" name="recipient_email" value="<?=h((string)($editConfig['recipient_email']??''))?>"></label></div><label class="check wide"><input type="checkbox" name="enabled" <?=!$editDestination||$editDestination['enabled']?'checked':''?>> Destination Enabled</label><div class="wide"><button>Save Destination</button></div></form></section><?php endif;?>

<?php elseif($section==='security'):?>
<section class="card"><h2>Security Settings</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="security"><label>Email Support Administrator<input type="email" name="support_email" value="<?=h(setting('support_email'))?>" <?=$readOnly?'readonly':''?>></label><label class="check"><input type="checkbox" name="enforce_2fa" <?=setting('enforce_2fa')==='1'?'checked':''?> <?=$readOnly?'disabled':''?>> Enforce 2FA For Enabled Accounts</label><p class="help">Enforcement requires every enabled database user to complete 2FA registration before it can be activated. Legacy administrator access remains available for recovery.</p><?php if(!$readOnly):?><button>Save Security Settings</button><?php endif;?></form></section>

<?php elseif($section==='email'):?>
<section class="card"><h2>Global System Email Account</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="email_global"><label>Hostname<input name="smtp_host" value="<?=h(setting('smtp_host'))?>" <?=$readOnly?'readonly':''?>></label><label>Port<input type="number" name="smtp_port" value="<?=h(setting('smtp_port','587'))?>" <?=$readOnly?'readonly':''?>></label><label>Connection Security<select name="smtp_security" <?=$readOnly?'disabled':''?>><option value="starttls">STARTTLS</option><option value="ssl" <?=setting('smtp_security')==='ssl'?'selected':''?>>TLS/SSL</option><option value="none" <?=setting('smtp_security')==='none'?'selected':''?>>None</option></select></label><label>Username<input name="smtp_user" value="<?=h(setting('smtp_user'))?>" <?=$readOnly?'readonly':''?>></label><label>Password<input type="password" name="smtp_password" placeholder="Leave blank to keep current value" <?=$readOnly?'readonly':''?>></label><label>From Email<input type="email" name="smtp_from" value="<?=h(setting('smtp_from'))?>" <?=$readOnly?'readonly':''?>></label><label>From Name<input name="smtp_from_name" value="<?=h(setting('smtp_from_name','NotifyRouter'))?>" <?=$readOnly?'readonly':''?>></label><label>Message Type<select name="email_message_type" <?=$readOnly?'disabled':''?>><option value="html">HTML</option><option value="plain" <?=setting('email_message_type')==='plain'?'selected':''?>>Plain Text</option></select></label><label class="wide">Common Email Footer<textarea name="email_footer" rows="4" <?=$readOnly?'readonly':''?>><?=h(setting('email_footer'))?></textarea></label><label>New User Welcome Subject<input name="welcome_subject" value="<?=h(setting('welcome_subject','Welcome To NotifyRouter'))?>" <?=$readOnly?'readonly':''?>></label><label class="wide">New User Welcome Template<textarea name="welcome_body" rows="7" <?=$readOnly?'readonly':''?>><?=h(setting('welcome_body','Hello {{ full_name }},&#10;&#10;Your username is {{ username }}.&#10;&#10;{{ reset_link }}'))?></textarea></label><label>Password Reset Subject<input name="reset_subject" value="<?=h(setting('reset_subject','NotifyRouter Password Reset'))?>" <?=$readOnly?'readonly':''?>></label><label class="wide">New User Password Reset Template<textarea name="reset_body" rows="7" <?=$readOnly?'readonly':''?>><?=h(setting('reset_body','Hello {{ full_name }},&#10;&#10;Use this link to reset your password: {{ reset_link }}'))?></textarea></label><?php if(!$readOnly):?><div class="wide"><button>Save Email Settings</button></div><?php endif;?></form></section>
<?php if(!$readOnly):?><section class="card"><h2>Test Email Templates</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="test_email_template"><label>User<select name="user_id" required><option value="">Select A User</option><?php foreach($users as$u):?><option value="<?=$u['id']?>"><?=h($u['full_name'].' · '.$u['email'])?></option><?php endforeach;?></select></label><label>Template<select name="template"><option value="welcome">New User Welcome</option><option value="reset">New User Password Reset</option></select></label><div class="wide"><button>Send Test Email</button></div></form></section><?php endif;?>

<?php elseif($section==='log'):
$auditRows=db()->query('SELECT * FROM audit_log ORDER BY id DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);?>
<section class="card"><div class="tilehead"><div><h2>System Audit Log</h2><p>Latest 500 events, newest first.</p></div></div><div class="table"><table><thead><tr><th>Date & Time</th><th>User</th><th>Event</th><th>Details</th></tr></thead><tbody><?php foreach($auditRows as$row):?><tr><td><?=h($row['occurred_at'])?></td><td><?=h($row['user_name'])?></td><td><?=h($row['event'])?></td><td><?=h($row['details'])?></td></tr><?php endforeach;?><?php if(!$auditRows):?><tr><td colspan="4">No Audit Events Yet</td></tr><?php endif;?></tbody></table></div></section>
<?php endif;?>
</div></div>
<script>
document.querySelectorAll('[data-destination-form]').forEach(form=>{const type=form.querySelector('[data-destination-type]');const sync=()=>form.querySelectorAll('[data-type]').forEach(group=>group.hidden=group.dataset.type!==type.value);type.addEventListener('change',sync);sync();});
</script>
<?php page_end();
