<?php
declare(strict_types=1);
define('NOTIFYROUTER_CONFIG',getenv('NOTIFYROUTER_CONFIG')?:dirname(__DIR__).'/.notifyrouter/config.php');
function cfg():array{$c=require NOTIFYROUTER_CONFIG;if(!is_array($c))throw new RuntimeException('Configuration unavailable');return$c;}
function db():PDO{static$d;if($d)return$d;$d=new PDO('sqlite:'.cfg()['database'],null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$d->exec('PRAGMA journal_mode=WAL;PRAGMA busy_timeout=5000');$d->exec("CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS rules(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,priority INTEGER NOT NULL DEFAULT 100,match_mode TEXT NOT NULL DEFAULT 'all',conditions TEXT NOT NULL DEFAULT '[]',title_template TEXT NOT NULL,message_template TEXT NOT NULL,html INTEGER NOT NULL DEFAULT 1,pushover_priority INTEGER NOT NULL DEFAULT 0,sound TEXT NOT NULL DEFAULT 'pushover',stop_processing INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,received_at TEXT NOT NULL,payload TEXT NOT NULL,variables TEXT NOT NULL,matched_rules TEXT NOT NULL,status TEXT NOT NULL)");return$d;}
function setting(string$k,string$x=''):string{$q=db()->prepare('SELECT value FROM settings WHERE key=?');$q->execute([$k]);$v=$q->fetchColumn();return$v===false?$x:(string)$v;}
function setv(string$k,string$v):void{$q=db()->prepare('INSERT INTO settings(key,value)VALUES(?,?) ON CONFLICT(key)DO UPDATE SET value=excluded.value');$q->execute([$k,$v]);}
function enc(string$v):string{if($v==='')return'';$k=sodium_base642bin(cfg()['master_key'],SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);$n=random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);return sodium_bin2base64($n.sodium_crypto_secretbox($v,$n,$k),SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);}
function dec(string$v):string{if($v==='')return'';try{$r=sodium_base642bin($v,SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);$n=substr($r,0,SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);$k=sodium_base642bin(cfg()['master_key'],SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);$p=sodium_crypto_secretbox_open(substr($r,SODIUM_CRYPTO_SECRETBOX_NONCEBYTES),$n,$k);return$p===false?'':$p;}catch(Throwable){return'';}}
function flat(mixed$v,string$p=''):array{$o=[];if($p!=='')$o[$p]=$v;if(is_array($v))foreach($v as$k=>$c)$o+=flat($c,$p===''?(string)$k:$p.'.'.$k);return$o;}
function vals(array$v,string$p):array{if(!str_contains($p,'*'))return array_key_exists($p,$v)?[$v[$p]]:[];$r='/^'.str_replace('\\*','[^.]+',preg_quote($p,'/')).'$/';return array_values(array_filter($v,fn($x,$k)=>preg_match($r,(string)$k)===1,ARRAY_FILTER_USE_BOTH));}
function cond(array$c,array$v):bool{$vs=vals($v,(string)($c['path']??''));$op=(string)($c['operator']??'equals');$w=$c['value']??null;if($op==='exists')return count($vs)>0;if($op==='not_exists')return count($vs)===0;foreach($vs as$a){$as=is_scalar($a)?(string)$a:json_encode($a);$ws=is_scalar($w)?(string)$w:json_encode($w);$ok=match($op){'equals'=>$a===$w||$as===$ws,'not_equals'=>!($a===$w||$as===$ws),'contains'=>str_contains($as,$ws),'starts_with'=>str_starts_with($as,$ws),'ends_with'=>str_ends_with($as,$ws),'regex'=>@preg_match('~'.$ws.'~',$as)===1,'gt'=>is_numeric($as)&&is_numeric($ws)&&(float)$as>(float)$ws,'gte'=>is_numeric($as)&&is_numeric($ws)&&(float)$as>=(float)$ws,'lt'=>is_numeric($as)&&is_numeric($ws)&&(float)$as<(float)$ws,'lte'=>is_numeric($as)&&is_numeric($ws)&&(float)$as<=(float)$ws,'in'=>in_array($as,is_array($w)?array_map('strval',$w):array_map('trim',explode(',',$ws)),true),default=>false};if($ok)return true;}return false;}
function render(string$t,array$v):string{return preg_replace_callback('/\{\{\s*([^{}]+?)\s*\}\}/',function($m)use($v){$x=$v[trim($m[1])]??'';if(is_array($x))$x=json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return htmlspecialchars((string)$x,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');},$t)??'';}
function evaluate(array$p):array{$v=flat($p);$out=[];foreach(db()->query('SELECT * FROM rules WHERE enabled=1 ORDER BY priority,id')->fetchAll(PDO::FETCH_ASSOC)as$r){$cs=json_decode($r['conditions'],true)?:[];$rs=array_map(fn($c)=>cond($c,$v),$cs);$m=$r['match_mode']==='any'?in_array(true,$rs,true):!in_array(false,$rs,true);if(!$m)continue;$out[]=['rule'=>$r['name'],'title'=>render($r['title_template'],$v),'message'=>render($r['message_template'],$v),'html'=>(bool)$r['html'],'priority'=>(int)$r['pushover_priority'],'sound'=>$r['sound']];if($r['stop_processing'])break;}return[$v,$out];}
function send(array$o):string{$t=dec(setting('pushover_token'));$u=dec(setting('pushover_user'));if($t===''||$u==='')return'not_configured';$ch=curl_init('https://api.pushover.net/1/messages.json');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>10,CURLOPT_POSTFIELDS=>['token'=>$t,'user'=>$u,'title'=>mb_substr($o['title'],0,250),'message'=>mb_substr($o['message'],0,1024),'html'=>$o['html']?1:0,'priority'=>$o['priority'],'sound'=>$o['sound']]]);curl_exec($ch);$c=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);return$c>=200&&$c<300?'sent':'failed:'.$c;}
function ses():void{if(session_status()!==PHP_SESSION_ACTIVE){$secure=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')||strtolower((string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))==='https';session_set_cookie_params(['httponly'=>true,'secure'=>$secure,'samesite'=>'Strict']);session_start();}}
function csrf():string{ses();return$_SESSION['csrf']??=$_SESSION['csrf']=bin2hex(random_bytes(24));}
function csrfok():void{ses();if(!hash_equals($_SESSION['csrf']??'',(string)($_POST['csrf']??''))){http_response_code(403);exit('Invalid request token');}}
function h(string$v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH);
if($path==='/alarmid.php'||$path==='/webhook'){header('Content-Type: application/json');if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['status'=>'method_not_allowed']);exit;}$c=cfg();$s=$_SERVER['HTTP_X_SIGNAL_GATEWAY_TOKEN']??($_GET['token']??'');if($c['webhook_token']!==''&&!hash_equals($c['webhook_token'],(string)$s)){http_response_code(401);echo json_encode(['status'=>'unauthorized']);exit;}$raw=file_get_contents('php://input');$p=json_decode($raw?:'',true);if(!is_array($p)){http_response_code(400);echo json_encode(['status'=>'invalid_json']);exit;}[$v,$o]=evaluate($p);$st=array_map('send',$o);$status=$st?implode(',',$st):'no_match';$q=db()->prepare('INSERT INTO events(received_at,payload,variables,matched_rules,status)VALUES(?,?,?,?,?)');$q->execute([gmdate(DATE_ATOM),json_encode($p),json_encode($v),json_encode(array_column($o,'rule')),$status]);http_response_code(202);echo json_encode(['accepted'=>true,'matched_rules'=>array_column($o,'rule'),'status'=>$status]);exit;}
ses();$setup=setting('admin_hash')==='';if($path==='/admin/setup'||$path==='/admin/setup/'){$ok=$setup&&hash_equals(cfg()['setup_token'],(string)($_GET['token']??$_POST['token']??''));$error='';if($_SERVER['REQUEST_METHOD']==='POST'&&$ok){$pw=(string)($_POST['password']??'');if(strlen($pw)<12)$error='Use at least 12 characters.';else{setv('admin_hash',password_hash($pw,PASSWORD_DEFAULT));header('Location:/admin');exit;}}page_start('Admin Setup');echo'<section class="card narrow"><h1>Admin Setup</h1>';if(!$setup)echo'<p>Setup is complete. <a href="/admin">Sign In</a>.</p>';elseif(!$ok)echo'<p class="error">A valid one-time setup link is required.</p>';else echo($error?'<p class="error">'.h($error).'</p>':'').'<p>Choose an administrator password. This link is disabled afterwards.</p><form method="post"><input type="hidden" name="token" value="'.h(cfg()['setup_token']).'"><label>New Password<input type="password" name="password" minlength="12" required autofocus></label><button>Complete Setup</button></form>';echo'</section>';page_end();exit;}
if($setup){header('Location:/admin/setup');exit;}if(empty($_SESSION['admin'])){if($_SERVER['REQUEST_METHOD']==='POST'&&password_verify((string)($_POST['password']??''),setting('admin_hash'))){session_regenerate_id(true);$_SESSION['admin']=true;$_SESSION['csrf']=bin2hex(random_bytes(24));header('Location:/admin');exit;}page_start('Admin Sign In');echo'<section class="card narrow"><h1>Admin Sign In</h1><form method="post"><label>Password<input type="password" name="password" required autofocus></label><button>Sign In</button></form></section>';page_end();exit;}
if($path==='/admin/inspect'){csrfok();header('Content-Type:application/json');$p=json_decode((string)($_POST['payload']??''),true);if(!is_array($p)){http_response_code(400);echo json_encode(['error'=>'Invalid JSON']);exit;}[$v,$o]=evaluate($p);echo json_encode(['variables'=>$v,'outputs'=>$o],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
$error='';if($_SERVER['REQUEST_METHOD']==='POST'){csrfok();$a=$_POST['action']??'';if($a==='logout'){session_destroy();header('Location:/admin');exit;}if($a==='settings'){setv('app_name',(string)($_POST['app_name']??'NotifyRouter'));foreach(['pushover_token','pushover_user']as$k)if((string)($_POST[$k]??'')!=='')setv($k,enc((string)$_POST[$k]));}if($a==='delete')db()->prepare('DELETE FROM rules WHERE id=?')->execute([(int)$_POST['id']]);if($a==='rule'){$cs=json_decode((string)($_POST['conditions']??'[]'),true);if(!is_array($cs))$error='Conditions must be valid JSON.';else{$x=[(string)$_POST['name'],isset($_POST['enabled'])?1:0,(int)$_POST['priority'],($_POST['match_mode']??'all')==='any'?'any':'all',json_encode($cs),(string)$_POST['title_template'],(string)$_POST['message_template'],isset($_POST['html'])?1:0,(int)$_POST['pushover_priority'],(string)$_POST['sound'],isset($_POST['stop_processing'])?1:0];if((int)($_POST['id']??0)>0){$q=db()->prepare('UPDATE rules SET name=?,enabled=?,priority=?,match_mode=?,conditions=?,title_template=?,message_template=?,html=?,pushover_priority=?,sound=?,stop_processing=? WHERE id=?');$x[]=(int)$_POST['id'];}else$q=db()->prepare('INSERT INTO rules(name,enabled,priority,match_mode,conditions,title_template,message_template,html,pushover_priority,sound,stop_processing)VALUES(?,?,?,?,?,?,?,?,?,?,?)');$q->execute($x);}}if($error===''){header('Location:/admin');exit;}}
function page_start(string$t):void{echo'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.h($t).'</title><link rel="stylesheet" href="/assets/style.css"></head><body><header><img src="/assets/logo.png" alt="NotifyRouter"></header><main>';}
function page_end():void{echo'</main></body></html>';}
$rules=db()->query('SELECT * FROM rules ORDER BY priority,id')->fetchAll(PDO::FETCH_ASSOC);$events=db()->query('SELECT received_at,matched_rules,status FROM events ORDER BY id DESC LIMIT 20')->fetchAll(PDO::FETCH_ASSOC);$configured=setting('pushover_token')!==''&&setting('pushover_user')!=='';page_start('NotifyRouter Admin');
?><div class="top"><div><h1>Rules &amp; Outputs</h1><p>Match any payload path and compose messages using <code>{{ variable.path }}</code>.</p></div><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="logout"><button class="secondary">Sign Out</button></form></div><?php if($error):?><p class="error"><?=h($error)?></p><?php endif;?>
<section class="grid"><article class="card"><h2>Pushover Settings</h2><p class="status"><?=$configured?'Configured':'Not Configured'?></p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="settings"><label>Application Name<input name="app_name" value="<?=h(setting('app_name','NotifyRouter'))?>"></label><label>Application API Token<input type="password" name="pushover_token" placeholder="Leave blank to keep current value"></label><label>User Or Group Key<input type="password" name="pushover_user" placeholder="Leave blank to keep current value"></label><button>Save Settings</button></form></article><article class="card"><h2>Payload Inspector</h2><p>Preview variables and outputs without sending.</p><form method="post" action="/admin/inspect" target="inspect-result"><input type="hidden" name="csrf" value="<?=csrf()?>"><textarea name="payload" rows="11">{"events":[{"alert_key":"CLIENT_CONNECTED","scope":{"site_id":"example"}}]}</textarea><button>Inspect Payload</button></form></article></section>
<section class="card"><h2>Create Or Update Rule</h2><form method="post" class="ruleform"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="rule"><label>Rule ID <span>Leave blank to create</span><input name="id" type="number"></label><label>Rule Name<input name="name" required></label><label>Priority<input name="priority" type="number" value="100"></label><label>Match Mode<select name="match_mode"><option value="all">All Conditions</option><option value="any">Any Condition</option></select></label><label class="wide">Conditions JSON<textarea name="conditions" rows="4">[{"path":"events.*.alert_key","operator":"equals","value":"CLIENT_CONNECTED"}]</textarea></label><label class="wide">Title Template<input name="title_template" value="UniFi: {{ events.0.alert_key }}"></label><label class="wide">Message Template<textarea name="message_template" rows="4">Event &lt;b&gt;{{ events.0.alert_key }}&lt;/b&gt; occurred at site {{ events.0.scope.site_id }}.</textarea></label><label>Pushover Priority<input name="pushover_priority" type="number" min="-2" max="2" value="0"></label><label>Sound<input name="sound" value="pushover"></label><label class="check"><input type="checkbox" name="enabled" checked> Enabled</label><label class="check"><input type="checkbox" name="html" checked> Enable HTML</label><label class="check"><input type="checkbox" name="stop_processing"> Stop After Match</label><button>Save Rule</button></form></section>
<section class="card"><h2>Rules</h2><div class="table"><table><tr><th>ID</th><th>Priority</th><th>Name</th><th>Conditions</th><th>Enabled</th><th></th></tr><?php foreach($rules as$r):?><tr><td><?=$r['id']?></td><td><?=$r['priority']?></td><td><?=h($r['name'])?></td><td><code><?=h($r['conditions'])?></code></td><td><?=$r['enabled']?'Yes':'No'?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach;?></table></div></section><section class="card"><h2>Recent Events</h2><div class="table"><table><tr><th>Received</th><th>Matched Rules</th><th>Status</th></tr><?php foreach($events as$e):?><tr><td><?=h($e['received_at'])?></td><td><?=h($e['matched_rules'])?></td><td><?=h($e['status'])?></td></tr><?php endforeach;?></table></div></section><?php page_end();
